# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_macosx
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

TARGETDIR = ../../build/bin
TARGET = $(TARGETDIR)/libioto.a
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LDDEPS +=
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_macosx)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
OBJDIR = ../../build/obj/ioto-macosx-debug
DEFINES += -DME_VERSION=\"3.1.0\" -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_COM_OPENSSL_PATH=\"/opt/homebrew\" -DME_DEBUG=1
INCLUDES += -I../../include -I/opt/homebrew/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -g -Wall -Wextra -std=gnu11 -Wno-sign-conversion -Wno-unused-parameter -Wno-unused-result -Wshorten-64-to-32 -Wall -Wno-unknown-warning-option -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -g -Wall -Wextra -Wno-sign-conversion -Wno-unused-parameter -Wno-unused-result -Wshorten-64-to-32 -Wall -Wno-unknown-warning-option -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -ldl -lpthread -lm
ALL_LDFLAGS += $(LDFLAGS) -g -Wl,-no_warn_duplicate_libraries -Wl,-rpath,@executable_path/ -Wl,-rpath,@loader_path/

else ifeq ($(config),debug_linux)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
OBJDIR = ../../build/obj/ioto-linux-debug
DEFINES += -DME_VERSION=\"3.1.0\" -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_COM_OPENSSL_PATH=\"/usr\" -DME_DEBUG=1
INCLUDES += -I../../include -I/usr/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -g -Wall -Wextra -std=gnu11 -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare -pie -fPIE
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -g -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare -pie -fPIE
LIBS += -lrt -ldl -lpthread -lm
ALL_LDFLAGS += $(LDFLAGS) -g -Wl,-z,relro,-z,now -Wl,--as-needed -Wl,--no-copy-dt-needed-entries -Wl,--no-warn-execstack

else ifeq ($(config),debug_freebsd)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
OBJDIR = ../../build/obj/ioto-freebsd-debug
DEFINES += -DME_VERSION=\"3.1.0\" -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_COM_OPENSSL_PATH=\"/usr\" -DME_DEBUG=1
INCLUDES += -I../../include -I/usr/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -g -Wall -Wextra -std=gnu11 -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -g -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -ldl -lpthread -lm
ALL_LDFLAGS += $(LDFLAGS) -g

else ifeq ($(config),release_macosx)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
OBJDIR = ../../build/obj/ioto-macosx-release
DEFINES += -DME_VERSION=\"3.1.0\" -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_COM_OPENSSL_PATH=\"/opt/homebrew\"
INCLUDES += -I../../include -I/opt/homebrew/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -Wextra -std=gnu11 -Wno-sign-conversion -Wno-unused-parameter -Wno-unused-result -Wshorten-64-to-32 -Wall -Wno-unknown-warning-option -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -Wextra -Wno-sign-conversion -Wno-unused-parameter -Wno-unused-result -Wshorten-64-to-32 -Wall -Wno-unknown-warning-option -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -ldl -lpthread -lm
ALL_LDFLAGS += $(LDFLAGS) -s -Wl,-no_warn_duplicate_libraries -Wl,-rpath,@executable_path/ -Wl,-rpath,@loader_path/

else ifeq ($(config),release_linux)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
OBJDIR = ../../build/obj/ioto-linux-release
DEFINES += -DME_VERSION=\"3.1.0\" -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_COM_OPENSSL_PATH=\"/usr\"
INCLUDES += -I../../include -I/usr/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -Wextra -std=gnu11 -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare -pie -fPIE
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare -pie -fPIE
LIBS += -lrt -ldl -lpthread -lm
ALL_LDFLAGS += $(LDFLAGS) -s -s -Wl,-z,relro,-z,now -Wl,--as-needed -Wl,--no-copy-dt-needed-entries -Wl,--no-warn-execstack

else ifeq ($(config),release_freebsd)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
OBJDIR = ../../build/obj/ioto-freebsd-release
DEFINES += -DME_VERSION=\"3.1.0\" -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_COM_OPENSSL_PATH=\"/usr\"
INCLUDES += -I../../include -I/usr/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -Wextra -std=gnu11 -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -ldl -lpthread -lm
ALL_LDFLAGS += $(LDFLAGS) -s -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/agent.o
GENERATED += $(OBJDIR)/ai.o
GENERATED += $(OBJDIR)/config.o
GENERATED += $(OBJDIR)/cron.o
GENERATED += $(OBJDIR)/cryptLib.o
GENERATED += $(OBJDIR)/database.o
GENERATED += $(OBJDIR)/dbLib.o
GENERATED += $(OBJDIR)/esp32.o
GENERATED += $(OBJDIR)/ioto.o
GENERATED += $(OBJDIR)/jsonLib.o
GENERATED += $(OBJDIR)/mqttLib.o
GENERATED += $(OBJDIR)/openaiLib.o
GENERATED += $(OBJDIR)/rLib.o
GENERATED += $(OBJDIR)/setup.o
GENERATED += $(OBJDIR)/uctxAssembly.o
GENERATED += $(OBJDIR)/uctxLib.o
GENERATED += $(OBJDIR)/urlLib.o
GENERATED += $(OBJDIR)/webLib.o
GENERATED += $(OBJDIR)/webserver.o
GENERATED += $(OBJDIR)/websockLib.o
OBJECTS += $(OBJDIR)/agent.o
OBJECTS += $(OBJDIR)/ai.o
OBJECTS += $(OBJDIR)/config.o
OBJECTS += $(OBJDIR)/cron.o
OBJECTS += $(OBJDIR)/cryptLib.o
OBJECTS += $(OBJDIR)/database.o
OBJECTS += $(OBJDIR)/dbLib.o
OBJECTS += $(OBJDIR)/esp32.o
OBJECTS += $(OBJDIR)/ioto.o
OBJECTS += $(OBJDIR)/jsonLib.o
OBJECTS += $(OBJDIR)/mqttLib.o
OBJECTS += $(OBJDIR)/openaiLib.o
OBJECTS += $(OBJDIR)/rLib.o
OBJECTS += $(OBJDIR)/setup.o
OBJECTS += $(OBJDIR)/uctxAssembly.o
OBJECTS += $(OBJDIR)/uctxLib.o
OBJECTS += $(OBJDIR)/urlLib.o
OBJECTS += $(OBJDIR)/webLib.o
OBJECTS += $(OBJDIR)/webserver.o
OBJECTS += $(OBJDIR)/websockLib.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo "        [AR] ioto"
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo "     [Clean] ioto"
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/cryptLib.o: ../../lib/cryptLib.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dbLib.o: ../../lib/dbLib.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/jsonLib.o: ../../lib/jsonLib.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mqttLib.o: ../../lib/mqttLib.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/openaiLib.o: ../../lib/openaiLib.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rLib.o: ../../lib/rLib.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/uctxAssembly.o: ../../lib/uctxAssembly.S
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/uctxLib.o: ../../lib/uctxLib.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/urlLib.o: ../../lib/urlLib.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/webLib.o: ../../lib/webLib.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/websockLib.o: ../../lib/websockLib.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/agent.o: ../../src/agent.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ai.o: ../../src/ai.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ioto.o: ../../src/cmds/ioto.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/config.o: ../../src/config.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cron.o: ../../src/cron.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/database.o: ../../src/database.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/esp32.o: ../../src/esp32.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/setup.o: ../../src/setup.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/webserver.o: ../../src/webserver.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif